### ISSUE TITLE
Sourcing a file inside the sourced file is not working

### ISSUE THREAD

**Issue by seydakhan** [dakusui/commandunit#38]
I have a script file(scriptA.sh) which sources scriptB.sh;
**scriptA.sh**
```
#!/usr/bin/env bash
  source scriptB.sh
```
when I create commandunit script such as below and source scriptA.sh, commandunit cannot find scriptB.sh file and giving ".../scriptA.sh: line 6: /dev/scriptB.sh: No such file or directory" error message.
**test.yaml**
```
"$extends":
  - some.json
when:
  source: 
   -scriptA.sh
  cmd:
then:
  exitCode:
    - EQUAL
    - 0
   ```

**Comment by dakusui** [comment]
Thanks.
Please include the exact error message so that I can think of what is going on.

**Comment by seydakhan** [comment]
> Thanks. Please include the exact error message so that I can think of what is going on.

Updated the description.

**Comment by dakusui** [comment]
This worked in my environment as designed for both docker and native modes.
I will update you soon with real examples.

**Comment by dakusui** [comment]
The following file worked without changing anything for current commandunit.
Can you please check your file's syntax?

https://github.com/dakusui/commandunit-installer/blob/master/src/test/scripts/core/test-target_function_sourced.yaml%2B%2B

```yaml
---
"$extends":
  - core/base.json
when:
  environmentVariables:
    SCRIPTS_DIR: "${COMMANDUNIT_PROJECT_DIR}/src/main/scripts"
  source:
    - ${COMMANDUNIT_BUILTIN_ROOT}/bud/lib/core.rc
    - ${SCRIPTS_DIR}/target_lib_source.rc
  cmd: target_function
  args:
    - Lisa
    - Gaspard
then:
  exitCode:
    - EQUAL
    - 0
  stdout:
    present:
      - REGEX:hello
      - REGEX:Lisa
    absent:
      - REGEX:Gaspard
  stderr:
    absent:
      - REGEX:.+
```
